=== jaimergp/external-metadata-mappings/schemas/external-mapping.schema.json
{
  "$id": "https://github.com/python/peps/blob/main/peps/pep-0XXX/central-registry.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "MappingWithSpecs": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "description": "PURL-like identifier, as provided in the central registry,\nbeing mapped to ecosystem specific packages.",
          "minLength": 5,
          "pattern": "^dep:.+$",
          "title": "Id",
          "type": "string"
        },
        "description": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Free-form field for details about the mapping. Allows Markdown.",
          "title": "Description"
        },
        "specs": {
          "anyOf": [
            {
              "minLength": 1,
              "type": "string"
            },
            {
              "items": {
                "minLength": 1,
                "type": "string"
              },
              "type": "array"
            },
            {
              "$ref": "#/$defs/SpecsDict"
            }
          ],
          "description": "Package specifiers that provide the identifier at `id`.",
          "title": "Specs"
        },
        "urls": {
          "anyOf": [
            {
              "format": "uri",
              "minLength": 1,
              "type": "string"
            },
            {
              "items": {
                "format": "uri",
                "minLength": 1,
                "type": "string"
              },
              "type": "array"
            },
            {
              "additionalProperties": {
                "format": "uri",
                "minLength": 1,
                "type": "string"
              },
              "propertyNames": {
                "minLength": 1
              },
              "type": "object"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Hyperlinks to web locations that provide more information about the mapping.",
          "title": "Urls"
        }
      },
      "required": [
        "id",
        "specs"
      ],
      "title": "MappingWithSpecs",
      "type": "object"
    },
    "MappingWithSpecsFrom": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "description": "PURL-like identifier, as provided in the central registry,\nbeing mapped to ecosystem specific packages.",
          "minLength": 5,
          "pattern": "^dep:.+$",
          "title": "Id",
          "type": "string"
        },
        "description": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Free-form field for details about the mapping. Allows Markdown.",
          "title": "Description"
        },
        "specs_from": {
          "description": "Identifier of another mapping entry with identical dependencies. Useful to avoid duplication.\nCannot be used together with `specs`.",
          "minLength": 5,
          "pattern": "^dep:.+$",
          "title": "Specs From",
          "type": "string"
        },
        "urls": {
          "anyOf": [
            {
              "format": "uri",
              "minLength": 1,
              "type": "string"
            },
            {
              "items": {
                "format": "uri",
                "minLength": 1,
                "type": "string"
              },
              "type": "array"
            },
            {
              "additionalProperties": {
                "format": "uri",
                "minLength": 1,
                "type": "string"
              },
              "propertyNames": {
                "minLength": 1
              },
              "type": "object"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Hyperlinks to web locations that provide more information about the mapping.",
          "title": "Urls"
        }
      },
      "required": [
        "id",
        "specs_from"
      ],
      "title": "MappingWithSpecsFrom",
      "type": "object"
    },
    "PackageManager": {
      "additionalProperties": false,
      "description": "Details of a particular package manager for this ecosystem.",
      "properties": {
        "name": {
          "description": "Name of the package manager",
          "minLength": 1,
          "title": "Name",
          "type": "string"
        },
        "commands": {
          "$ref": "#/$defs/PackageManagerCommands"
        },
        "version_operators": {
          "$ref": "#/$defs/VersionOperators",
          "default": {
            "and": ",",
            "arbitrary": "===",
            "compatible": "~=",
            "equal": "==",
            "greater_than": ">",
            "greater_than_equal": ">=",
            "less_than": "<",
            "less_than_equal": "<=",
            "not_equal": "!=",
            "separator": ""
          },
          "description": "Mapping of PEP440 version comparison operators to the syntax used in this package manager.\nIf set to an empty dictionary, it means that the package manager (or ecosystem)\ndoesn't support the notion of requesting particular package versions."
        }
      },
      "required": [
        "name",
        "commands"
      ],
      "title": "PackageManager",
      "type": "object"
    },
    "PackageManagerCommand": {
      "additionalProperties": false,
      "description": "Command template plus its elevation requirements.",
      "properties": {
        "command": {
          "default": [],
          "description": "Command template, as expected by `subprocess.run`. Use `{}` as a placeholder for package(s).",
          "items": {
            "minLength": 1,
            "type": "string"
          },
          "title": "Command",
          "type": "array"
        },
        "requires_elevation": {
          "default": false,
          "description": "Whether the command requires elevated permissions to run.",
          "title": "Requires Elevation",
          "type": "boolean"
        }
      },
      "title": "PackageManagerCommand",
      "type": "object"
    },
    "PackageManagerCommands": {
      "additionalProperties": false,
      "description": "Command templates needed to execute certain operations with this package manager",
      "properties": {
        "install": {
          "$ref": "#/$defs/PackageManagerCommand",
          "description": "Command that must be used to install the given package(s). The tool must accept several\npackages in the same command. Each argument must be provided as a separate string, as\nin `subprocess.run`. Use `{}` as a placeholder where the package spec(s) must be injected.\nThe placeholder can only appear once in the whole list and will be replaced once per package.\nFor example, given the names `foo` and `bar`, `[\"pkg\", \"install\", \"{}\"]` would become\n`pkg install foo bar`, and `[\"pkg\", \"install\", \"--spec={}\"]` would become\n`pkg install --spec=foo --spec=bar`."
        },
        "query": {
          "anyOf": [
            {
              "$ref": "#/$defs/PackageManagerCommand"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Command to check whether a package is installed. The tool must only accept one package at a\ntime. Each argument must be provided as a separate string, as in `subprocess.run`. The `{}`\nplaceholder will be replaced by the single package. An empty list means no query command is\navailable for this package manager."
        }
      },
      "required": [
        "install"
      ],
      "title": "PackageManagerCommands",
      "type": "object"
    },
    "SpecsDict": {
      "additionalProperties": false,
      "properties": {
        "build": {
          "anyOf": [
            {
              "minLength": 1,
              "type": "string"
            },
            {
              "items": {
                "minLength": 1,
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Dependencies that must be present at build time and can be executed in the build machine.",
          "title": "Build"
        },
        "host": {
          "anyOf": [
            {
              "minLength": 1,
              "type": "string"
            },
            {
              "items": {
                "minLength": 1,
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Dependencies that must be present at build time but only for linking purposes.\nTheir architecture does not need to match the build machine.",
          "title": "Host"
        },
        "run": {
          "anyOf": [
            {
              "minLength": 1,
              "type": "string"
            },
            {
              "items": {
                "minLength": 1,
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "description": "Dependencies needed at runtime in the end-user machines.",
          "title": "Run"
        }
      },
      "title": "SpecsDict",
      "type": "object"
    },
    "VersionOperators": {
      "additionalProperties": false,
      "description": "Mapping of a PEP440 operator to a package manager specific operator.\nUse an empty string if there's no equivalent.",
      "properties": {
        "and": {
          "default": ",",
          "title": "And",
          "type": "string"
        },
        "arbitrary": {
          "default": "===",
          "title": "Arbitrary",
          "type": "string"
        },
        "compatible": {
          "default": "~=",
          "title": "Compatible",
          "type": "string"
        },
        "equal": {
          "default": "==",
          "title": "Equal",
          "type": "string"
        },
        "greater_than": {
          "default": ">",
          "title": "Greater Than",
          "type": "string"
        },
        "greater_than_equal": {
          "default": ">=",
          "title": "Greater Than Equal",
          "type": "string"
        },
        "less_than": {
          "default": "<",
          "title": "Less Than",
          "type": "string"
        },
        "less_than_equal": {
          "default": "<=",
          "title": "Less Than Equal",
          "type": "string"
        },
        "not_equal": {
          "default": "!=",
          "title": "Not Equal",
          "type": "string"
        },
        "separator": {
          "default": "",
          "title": "Separator",
          "type": "string"
        }
      },
      "title": "VersionOperators",
      "type": "object"
    }
  },
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "default": "",
      "description": "URL of the mappings schema in use for the document.",
      "title": "$Schema",
      "type": "string"
    },
    "schema_version": {
      "default": 1,
      "exclusiveMaximum": 2,
      "minimum": 1,
      "title": "Schema Version",
      "type": "integer"
    },
    "name": {
      "description": "Name of the schema",
      "minLength": 1,
      "title": "Name",
      "type": "string"
    },
    "description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "description": "Free-form field to add information this mapping. Allows Markdown.",
      "title": "Description"
    },
    "mappings": {
      "description": "List of PURL-to-specs mappings.",
      "items": {
        "anyOf": [
          {
            "$ref": "#/$defs/MappingWithSpecs"
          },
          {
            "$ref": "#/$defs/MappingWithSpecsFrom"
          }
        ]
      },
      "title": "Mappings",
      "type": "array"
    },
    "package_managers": {
      "description": "List of tools that can be used to install packages in this ecosystem.",
      "items": {
        "$ref": "#/$defs/PackageManager"
      },
      "title": "Package Managers",
      "type": "array"
    }
  },
  "required": [
    "name",
    "package_managers",
    "mappings"
  ],
  "title": "MappingsModel",
  "type": "object"
}

=== jaimergp/external-metadata-mappings/data/vcpkg.mapping.json
{
  "$schema": "https://raw.githubusercontent.com/jaimergp/external-metadata-mappings/main/schemas/external-mapping.schema.json",
  "schema_version": 1,
  "name": "vcpkg",
  "description": "Mapping for the vcpkg ecosystem",
  "mappings": [
    {
      "id": "dep:generic/arrow",
      "description": "Cross-language development platform for in-memory analytics",
      "specs": "arrow",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/arrow"
      }
    },
    {
      "id": "dep:generic/clang",
      "description": "Not available",
      "specs": []
    },
    {
      "id": "dep:generic/cmake",
      "description": "Not available",
      "specs": "vcpkg-cmake",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/vcpkg-cmake"
      }
    },
    {
      "id": "dep:generic/freetype",
      "description": "A library to render fonts.",
      "specs": "freetype",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/freetype"
      }
    },
    {
      "id": "dep:generic/gmp",
      "description": "GNU multiple precision arithmetic library",
      "specs": "gmp",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/gmp"
      }
    },
    {
      "id": "dep:generic/lcms2",
      "description": "Little CMS",
      "specs": "lcms",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/lcms"
      }
    },
    {
      "id": "dep:generic/libffi",
      "description": "Portable, high level programming interface to various calling conventions",
      "specs": "libffi",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/libffi"
      }
    },
    {
      "id": "dep:generic/libimagequant",
      "description": "Not available",
      "specs": []
    },
    {
      "id": "dep:generic/libjpeg",
      "description": "Independent JPEG Group's JPEG software",
      "specs": "igj-libjpeg",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/igj-libjpeg"
      }
    },
    {
      "id": "dep:generic/libjpeg",
      "description": "libjpeg-turbo is a JPEG image codec that uses SIMD instructions (MMX, SSE2, NEON, AltiVec) to accelerate baseline JPEG compression and decompression on x86, x86-64, ARM, and PowerPC systems",
      "specs": "libjpeg-turbo",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/libjpeg-turbo"
      }
    },
    {
      "id": "dep:generic/libpq",
      "description": "The official database access API of postgresql",
      "specs": "libpq",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/libpq"
      }
    },
    {
      "id": "dep:generic/libraqm",
      "description": "Library for complex text layout",
      "specs": "libraqm",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/libraqm"
      }
    },
    {
      "id": "dep:generic/libtiff",
      "description": "A library that supports the manipulation of TIFF image files",
      "specs": "tiff",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/tiff"
      }
    },
    {
      "id": "dep:generic/libwebp",
      "description": "WebP codec: library to encode and decode images in WebP format",
      "specs": "libwebp",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/libwebp"
      }
    },
    {
      "id": "dep:generic/libxcb",
      "description": "C interface to the X Window System protocol, which replaces the traditional Xlib interface.",
      "specs": "xcb",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/xcb"
      }
    },
    {
      "id": "dep:generic/libxml2",
      "description": "Libxml2 is the XML C parser and toolkit developed for the Gnome project (but usable outside of the Gnome platform).",
      "specs": "libxml2",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/libxml2"
      }
    },
    {
      "id": "dep:generic/libxslt",
      "description": "Libxslt is a XSLT library implemented in C for XSLT 1.0 and most of EXSLT",
      "specs": "libxslt",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/libxslt"
      }
    },
    {
      "id": "dep:generic/libyaml",
      "description": "A C library for parsing and emitting YAML.",
      "specs": "libyaml",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/libyaml"
      }
    },
    {
      "id": "dep:generic/llvm",
      "description": "The LLVM Compiler Infrastructure.",
      "specs": "llvm",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/llvm"
      }
    },
    {
      "id": "dep:generic/make",
      "description": "Not available",
      "specs": []
    },
    {
      "id": "dep:generic/ninja",
      "description": "Not available",
      "specs": []
    },
    {
      "id": "dep:generic/openblas",
      "description": "OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version.",
      "specs": "openblas",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/openblas"
      }
    },
    {
      "id": "dep:generic/openjpeg",
      "description": "OpenJPEG is an open-source JPEG 2000 codec written in C language. It has been developed in order to promote the use of JPEG 2000, a still-image compression standard from the Joint Photographic Experts Group (JPEG). Since April 2015, it is officially recognized by ISO/IEC and ITU-T as a JPEG 2000 Reference Software.",
      "specs": "openjpeg",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/openjpeg"
      }
    },
    {
      "id": "dep:generic/openssl",
      "description": "OpenSSL is an open source project that provides a robust, commercial-grade, and full-featured toolkit for the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols. It is also a general-purpose cryptography library.",
      "specs": "openssl",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/openssl"
      }
    },
    {
      "id": "dep:generic/pkg-config",
      "description": "pkgconf is a program which helps to configure compiler and linker flags for development libraries. It is similar to pkg-config from freedesktop.org.",
      "specs": "pkgconf",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/pkgconf"
      }
    },
    {
      "id": "dep:generic/pkg-config",
      "description": "Not available",
      "specs": []
    },
    {
      "id": "dep:generic/python",
      "description": "The Python programming language.",
      "specs": "python3",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/python3"
      }
    },
    {
      "id": "dep:generic/tk",
      "description": "Not available",
      "specs": []
    },
    {
      "id": "dep:generic/zlib",
      "description": "A compression library",
      "specs": "zlib",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/zlib"
      }
    },
    {
      "id": "dep:github/Reference-LAPACK/lapack",
      "description": "LAPACK - Linear Algebra PACKage",
      "specs": "lapack-reference",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/lapack-reference"
      }
    },
    {
      "id": "dep:virtual/compiler/c",
      "description": "Not available",
      "specs": []
    },
    {
      "id": "dep:virtual/compiler/c-sharp",
      "description": "Compiler for the C# language",
      "specs": [],
      "urls": {}
    },
    {
      "id": "dep:virtual/compiler/cuda",
      "description": "Compiler for the CUDA language",
      "specs": [],
      "urls": {}
    },
    {
      "id": "dep:virtual/compiler/cxx",
      "description": "Not available",
      "specs": []
    },
    {
      "id": "dep:virtual/compiler/fortran",
      "description": "Metaport to install gfortran dependencies from msys if VCPKG_USE_EXTERNAL_Fortran is false",
      "specs": "vcpkg-gfortran",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/vcpkg-gfortran"
      }
    },
    {
      "id": "dep:virtual/compiler/go",
      "description": "Compiler for the Go language",
      "specs": [],
      "urls": {}
    },
    {
      "id": "dep:virtual/compiler/javascript",
      "description": "Compiler for the JavaScript language",
      "specs": [],
      "urls": {}
    },
    {
      "id": "dep:virtual/compiler/obj-c",
      "description": "Compiler for the Objective C language",
      "specs": [],
      "urls": {}
    },
    {
      "id": "dep:virtual/compiler/obj-cxx",
      "description": "Compiler for the Objective C++ language",
      "specs": [],
      "urls": {}
    },
    {
      "id": "dep:virtual/compiler/ocaml",
      "description": "Compiler for the OCaml language",
      "specs": [],
      "urls": {}
    },
    {
      "id": "dep:virtual/compiler/rust",
      "description": "Not available",
      "specs": []
    },
    {
      "id": "dep:virtual/compiler/swift",
      "description": "Compiler for the Swift language",
      "specs": [],
      "urls": {}
    },
    {
      "id": "dep:virtual/compiler/typescript",
      "description": "Compiler for the TypeScript language",
      "specs": [],
      "urls": {}
    },
    {
      "id": "dep:virtual/compiler/zig",
      "description": "Compiler for the Zig language",
      "specs": [],
      "urls": {}
    },
    {
      "id": "dep:virtual/interface/blas",
      "description": "Metapackage for packages which provide BLAS",
      "specs": "blas",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/blas"
      }
    },
    {
      "id": "dep:virtual/interface/blas",
      "description": "OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version.",
      "specs": "openblas",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/openblas"
      }
    },
    {
      "id": "dep:virtual/interface/blas",
      "description": "clBLAS is an OpenCL 1.2 accelerated BLAS (Basic Linear Algebra Subsystem) library.",
      "specs": "clblas",
      "urls": {
        "vcpkg.io": "https://vcpkg.io/en/package/clblast"
      }
    },
    {
      "id": "dep:virtual/interface/blas",
